# Get all contacts
GET http://localhost:3000/contacts

###

# Get single contact by ID (replace with a real _id from your DB)
GET http://localhost:3000/contacts/69fb7e1f1817f92fb29d4341

###

# Create a contact
POST http://localhost:3000/contacts
Content-Type: application/json

{
  "firstName": "Taylor",
  "lastName": "Brown",
  "email": "taylor.b@email.com",
  "favoriteColor": "purple",
  "birthday": "2001-05-20"
}

###

# Update a contact
PUT http://localhost:3000/contacts/69fb7e1f1817f92fb29d4341
Content-Type: application/json

{
  "firstName": "Josh",
  "lastName": "Wagstaff",
  "email": "josh.updated@email.com",
  "favoriteColor": "green",
  "birthday": "2000-01-15"
}

###

# Delete a contact
DELETE http://localhost:3000/contacts/69fb7e1f1817f92fb29d4343

###

# Test live on Render - get all
GET https://CSE341Contacts.onrender.com/contacts

###

# Test live on Render - get single contact
GET https://CSE341Contacts.onrender.com/contacts/69fb7e1f1817f92fb29d4341
